---

- name: Check Provisioner
  import_role:
    name: kubernetes/common
    tasks_from: kube_check
  vars:
    type: "pods"
    namespace: "kube-system"
    resource_name: ""
    label: "app=rbd-provisioner"

- name: Get Ceph Health
  shell:  ceph health
  register: ceph_status_result
  failed_when: ceph_status_result.rc != 127 and ceph_status_result.rc != 0 and ceph_status_result.rc != 1

...
