---
- name: Create installation directory
  file:
    path: "{{ install_dir }}"
    owner: "{{ install_user }}"
    group: "{{ install_group }}"
    mode: 755
    state: directory

- name: Create logging directories on nodes
  file:
    path: "{{ log_dir }}"
    owner: root
    group: root
    mode: 0644
    state: directory

- name: Create logging directory on controller
  local_action:
    module: file
    path: "{{ log_dir }}"
    owner: root
    group: root
    mode: 0644
    state: directory

...