#######################################################
###################  Kubernetes Reset ###############
#######################################################
---
- name: Reset Kubernetes Node
  command: kubeadm reset
  register: kube_reset_result
  ignore_errors: yes

- name: Stop Services
  systemd:
    name: "{{ item }}"
    state: stopped
  ignore_errors: yes
  with_items:
    - docker
    - kubelet

- name: Remove Kubernetes Packages to clear cache
  yum:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: absent
  ignore_errors: yes

- name: Remove Artifacts
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/cni
    - /var/lib/kubelet
    - /etc/cni
    - /etc/kubernetes
    - /var/lib/etcd
    - ~/.kube
  register: remove_artifacts_result
  failed_when: "'Device or resource busy' in remove_artifacts_result"

- name: Delete Kubernetes directory
  file:
    path: "{{ kube_dir }}"
    state: absent

- name: Remove Interfaces
  shell: |
    ip link delete {{ item }};
  with_items:
    - flannel.1
    - cni0
  ignore_errors: yes
