---

- name: Install template for {{ filename }}
  template:
    src: "templates/{{ filename }}.j2"
    dest: "{{ bro_dir }}/{{ hostname }}-{{ filename }}"
    group: root
    owner: root
    mode: 0644

...