---

- name: Delete Bro Deployments
  include: 20_cleanup_bro.yml hostname="{{ item[0] }}" filename="{{ item[1] }}"
  with_nested:
    - "{{ groups['sensors'] | union(groups['remote-sensors']) }}"
    - ['deploy.yml']

- name: "Wait for deployment to cleanup"
  shell: |
    while [ $(kubectl get pods | grep bro | wc -l) -gt 0 ]; do
      echo -n .;
      sleep 1;
    done;

...