---

- import_tasks: 05_files.yml

- import_tasks: 15_cleanup.yml
  when: inventory_hostname in groups['master-server']

- import_tasks: 25_install.yml
  when: inventory_hostname in groups['master-server']

...