---
# TFPlenum
version: 3.0
debug_enabled: true
install_user: root
install_group: root
install_dir: /opt/tfplenum
log_dir: /var/log/ansible/hosts/
fqdn: default.svc.cluster.local

# Redis
redis_sentinel_port: 26379

# Elasticsearch
elastic_cluster_name: tfplenum
elastic_fqdn: "elasticsearch.{{ fqdn }}"
elastic_shortname: elasticsearch
elastic_port: 9200
kibana_port: 5601

# Kibana
kibana_fqdn: "kibana.{{ fqdn }}"

# If you have licensing for x-pack set variable to true.
xpack_license: 'true'

# Kubernetes
kubernetes_conf_file: /etc/kubernetes/admin.conf
kube_dir: "{{ install_dir }}/kubernetes"

# Kafka
kafka_fqdn: "kafka.{{ fqdn }}"
kafka_port: 9092
kafka_retention: 168

# Username and password for Web login
moloch_login: 'assessor'
moloch_pass: 'password'

# Directories in which to store IDS scripts/rules on sensors
bro_script_dir: /bro-scripts
suri_rule_dir: /suri-rules

# Common
package_list:
  - python-gobject
  - python-docker-py.noarch
  - nload
  - iperf
  - python-netaddr
  - openvpn
  - easy-rsa
  - bridge-utils
  - net-tools

ansible_controller_hostname: "controller.lan"
ansible_controller_ip: "{{ ansible_env[\"SSH_CLIENT\"].split()[0] }}"

offline_repo_base: "http://{{ ansible_controller_hostname }}/offlinerepo"
docker_registry_port: 5000
docker_registry_repo: "{{ ansible_controller_hostname }}:{{ docker_registry_port }}"
CentOS_Repos:
  - "CentOS-Base"
  - "CentOS-CR"
  - "CentOS-Debuginfo"
  - "CentOS-fasttrack"
  - "CentOS-Media"
  - "CentOS-Sources"
  - "CentOS-Vault"
...
