apiVersion: v1
kind: Service
metadata:
  labels:
    component: mumble-server
  name: mumble-server
spec:
  ports:
  - name: "voip"
    port: {{mumble_port}}
    targetPort: {{ mumble_port }}
  selector:
    component: mumble-server
  type: LoadBalancer