#######################################################
###################  Kubernetes Setup Nodes ###############
#######################################################
---
- name: Kube | Retrieve generated credentials
  import_role:
    name: kubernetes/common
    tasks_from: creds

- name: Kube | Copy join node cmd to nodes
  copy:
    src: 'files/join-node.sh'
    dest: '/etc/kubernetes/join-node.sh'
    mode: 0755

- name: Kube | Join Kubernetes cluster
  shell: '/etc/kubernetes/join-node.sh'

- name: Kube | Wait for Nodes to Register
  pause:
    seconds: 10

- name: Kube | Wait for Node to be ready
  import_role:
    name: kubernetes/common
    tasks_from: kube_wait
  vars:
    type: "node"
    namespace: ""
    resource_name: "{{ ansible_fqdn }}"
    label: ""

- name: Kube | Label sensors
  command: 'kubectl label nodes {{ ansible_fqdn }} role=sensor --overwrite=true'
  when: inventory_hostname in groups['sensors']

- name: Kube | Label secondary servers
  command: 'kubectl label nodes {{ ansible_fqdn }} role=server --overwrite=true'
  when: inventory_hostname in groups['servers']
  register: debug_output
