---
- name: Kube | Label remote sensors
  command: 'kubectl label nodes {{ ansible_fqdn }} role=remote-sensor --overwrite=true'
  when: inventory_hostname in groups['remote-sensors']

- name: Kube | Create Host Storage Directory
  file:
    path: "{{ item }}"
    mode: u+rw,g+rw
    owner: root
    group: root
    state: directory
  when: inventory_hostname in groups['remote-sensors']
  with_items:
    - "/data/kafka"
    - "/data/zookeeper/data"
    - "/data/zookeeper/datalog"