---

- name: Copy Files
  copy:
    src: "{{ item }}.yml"
    dest: "{{ kube_dir }}/{{ item }}.yml"
    owner: root
    group: root
    mode: 0644
  with_items:
    - heapster
    - grafana
    - influxdb
    - heapster-rbac

- name: Install Heapster
  command: "kubectl apply -f {{ kube_dir }}/heapster.yml"
  until: task_result.rc == 0
  retries: 10
  delay: 5
  register: task_result
  ignore_errors: yes

- name: Install Grafana
  command: "kubectl apply -f {{ kube_dir }}/grafana.yml"
  until: task_result.rc == 0
  retries: 10
  delay: 5
  register: task_result
  ignore_errors: yes

- name: Install InfluxDB
  command: "kubectl apply -f {{ kube_dir }}/influxdb.yml"
  until: task_result.rc == 0
  retries: 10
  delay: 5
  register: task_result
  ignore_errors: yes

- name: Install RBAC
  command: "kubectl apply -f {{ kube_dir }}/heapster-rbac.yml"
  until: task_result.rc == 0
  retries: 10
  delay: 5
  register: task_result
  ignore_errors: yes
