#######################################################
###################  Kubernetes Setup Master ###############
#######################################################
---

- import_tasks: 00_preflight.yml

- name: Master Node Block
  block:
    - import_tasks: 05_files.yml
    - import_tasks: 10_init_cluster.yml
    - import_tasks: 15_setup_master_node.yml

- import_tasks: 20_metallb.yml
- import_tasks: 25_kube_dashboard.yml
- import_tasks: 30_heapster.yml

- name: Label master node with appropriate roles
  import_role:
    name: kubernetes/common
    tasks_from: label_nodes.yml

- import_tasks: 35_configure_dns.yml

...
