---

############################################
# Checking that required variables are set #
############################################

- name: Check if remote-sensors is defined
  fail:
    msg: 'Verify you have the remote-sensors group in your inventory file. It must be defined. See sample inventory. If you have no remote sensors you can define an empty group with just remote-senors: under nodes.'
  when: "'remote-sensors' not in groups"

- name: Check if servers is defined
  fail:
    msg: 'Verify you have the servers group in your inventory file. It must be defined. See sample inventory. If you have no servers you can define an empty group with just servers: under nodes.'
  when: "'servers' not in groups"

- name: Checking that management_ipv4 is set
  fail:
    msg: "management_ipv4 is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: management_ipv4 is not defined or management_ipv4 is none

- name: Checking that home_net is set
  fail:
    msg: "home_net is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: home_net is not defined or home_net is none

- name: Checking that kubernetes_services_cidr is set
  fail:
    msg: "kubernetes_services_cidr is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: kubernetes_services_cidr is not defined or kubernetes_services_cidr is none

- name: Ensuring there is no ceph drive declared for a remote sensor
  fail:
     msg: "You have declared a ceph drive for a remote sensor. Remote sensors cannot be part of the ceph cluster; please remove this drive."
  when: inventory_hostname in groups['remote-sensors'] and (ceph_drive_list is defined and ceph_drive_list is not none and ceph_drive_list | length > 0)

- name: Checking that moloch_bpf is set
  fail:
    msg: "moloch_bpf is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_bpf is not defined or moloch_bpf is none

- name: Checking that bro_cpu_request is set
  fail:
    msg: "bro_cpu_request is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: bro_cpu_request is not defined or bro_cpu_request is none

- name: Checking that moloch_cpu_request is set
  fail:
    msg: "moloch_cpu_request is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_cpu_request is not defined or moloch_cpu_request is none

- name: Checking that suricata_cpu_request is set
  fail:
    msg: "suricata_cpu_request is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: suricata_cpu_request is not defined or suricata_cpu_request is none

- name: Checking that kafka_cpu_request is set
  fail:
    msg: "kafka_cpu_request is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: kafka_cpu_request is not defined or kafka_cpu_request is none

- name: Checking that zookeeper_cpu_request is set
  fail:
    msg: "zookeeper_cpu_request is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: zookeeper_cpu_request is not defined or zookeeper_cpu_request is none

- name: Checking that logstash_cpu_request is set
  fail:
    msg: "logstash_cpu_request is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: logstash_cpu_request is not defined or logstash_cpu_request is none

- name: Checking that elasticsearch_cpu_request is set
  fail:
    msg: "elasticsearch_cpu_request is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: elasticsearch_cpu_request is not defined or elasticsearch_cpu_request is none

- name: Checking that elastic_memory is set
  fail:
    msg: "elastic_memory is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: elastic_memory is not defined or elastic_memory is none

- name: Checking that elastic_masters is set
  fail:
    msg: "elastic_masters is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: elastic_masters is not defined or elastic_masters is none

- name: Checking that moloch_dontSaveBPFs is set
  fail:
    msg: "moloch_dontSaveBPFs is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_dontSaveBPFs is not defined or moloch_dontSaveBPFs is none

- name: Checking that elastic_datas is set
  fail:
    msg: "elastic_datas is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: elastic_datas is not defined or elastic_datas is none

- name: Checking that elastic_pv_size
  fail:
    msg: "elastic_pv_size is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: elastic_pv_size is not defined or elastic_pv_size is none

- name: Checking that kafka_pv_size is set
  fail:
    msg: "kafka_pv_size is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: kafka_pv_size is not defined or kafka_pv_size is none

- name: Checking that zookeeper_pv_size is set
  fail:
    msg: "zookeeper_pv_size is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: zookeeper_pv_size is not defined or zookeeper_pv_size is none

- name: Checking that zookeeper_replicas is set
  fail:
    msg: "zookeeper_replicas is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: zookeeper_replicas is not defined or zookeeper_replicas is none

- name: Checking that moloch_pcap_pv_size is set
  fail:
    msg: "moloch_pcap_pv_size is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_pcap_pv_size is not defined or moloch_pcap_pv_size is none

- name: Checking that zookeeper_mem is set
  fail:
    msg: "zookeeper_mem is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: zookeeper_mem is not defined or zookeeper_mem is none

- name: Checking that kakfa_mem is set
  fail:
    msg: "kafka_jvm_memory is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: kafka_jvm_memory is not defined or kafka_jvm_memory is none

- name: Checking that sensor_monitor_interface is set
  fail:
    msg: "sensor_monitor_interface is not defined or sensor_monitor_interface is not a list. Make sure it is defined in your inventory file. See sample inventory for help. All sensors must have monitor interface defined."
  when: inventory_hostname in groups['sensors'] and (sensor_monitor_interface is not defined or sensor_monitor_interface is none or sensor_monitor_interface is string or sensor_monitor_interface is not iterable)

- name: Checking that bro_wokers is set
  fail:
    msg: "bro_workers is not defined. Make sure it is defined in your inventory file. See sample inventory for help. This host is in the bro group and subsequently must have a bro workers count. Keep in mind bro_workers must be non-zero. If you want to get rid of bro, take the host out of the bro group."
  when: inventory_hostname in groups['bro'] and (bro_workers is not defined or bro_wokers is none or (bro_workers | int) == 0)

- name: Checking that moloch_spiDataMaxIndices is set
  fail:
    msg: "moloch_spiDataMaxIndices is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_spiDataMaxIndices is not defined or moloch_spiDataMaxIndices is none

- name: Checking that moloch_pcapWriteMethod is set
  fail:
    msg: "moloch_pcapWriteMethod is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_pcapWriteMethod is not defined or moloch_pcapWriteMethod is none

- name: Checking that moloch_packet_v3_block_size is set
  fail:
    msg: "moloch_packet_v3_block_size is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_packet_v3_block_size is not defined or moloch_packet_v3_block_size is none

- name: Checking that moloch_packet_v3_num_threads is set
  fail:
    msg: "moloch_packet_v3_num_threads is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_packet_v3_num_threads is not defined or moloch_packet_v3_num_threads is none

- name: Checking that moloch_pcapWriteSize is set
  fail:
    msg: "moloch_pcapWriteSize is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_pcapWriteSize is not defined or moloch_pcapWriteSize is none

- name: Checking that moloch_pcapWriteMethod is set
  fail:
    msg: "moloch_pcapWriteMethod is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_pcapWriteMethod is not defined or moloch_pcapWriteMethod is none

- name: Checking that moloch_maxESConns is set
  fail:
    msg: "moloch_maxESConns is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_maxESConns is not defined or moloch_maxESConns is none

- name: Checking that moloch_maxESRequests is set
  fail:
    msg: "moloch_maxESRequests is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_maxESRequests is not defined or moloch_maxESRequests is none

- name: Checking that moloch_packetsPerPoll is set
  fail:
    msg: "moloch_packetsPerPoll is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_packetsPerPoll is not defined or moloch_packetsPerPoll is none

- name: Checking that moloch_magicMode is set
  fail:
    msg: "moloch_magicMode is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_magicMode is not defined or moloch_magicMode is none

- name: Checking that moloch_maxPacketsInQueue is set
  fail:
    msg: "moloch_maxPacketsInQueue is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: moloch_maxPacketsInQueue is not defined or moloch_maxPacketsInQueue is none

- name: Checking that use_ceph_for_pcap is set
  fail:
    msg: "use_ceph_for_pcap is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: use_ceph_for_pcap is not defined or use_ceph_for_pcap is none

- name: Checking that moloch_pcap_folder is set
  fail:
    msg: "moloch_pcap_folder is not defined. Make sure it is defined in your inventory file. See sample inventory for help. You do not have to provide a value, but it must exist in the inventor file. Add moloch_pcap_folder: to inventory in all vars to resolve this error."
  when: moloch_pcap_folder is not defined

- name: Checking moloch_pcap_pv_size is not set if not using ceph for pcap
  fail:
    msg: "You have set use_ceph_for_pcap to false indicating you do not intend to use it for PCAP storage, but provided a non-zero definition to moloch_pcap_pv_size. Set moloch_pcap_pv_size to zero or change the value of use_ceph_for_pcap to true."
  when: not use_ceph_for_pcap and (moloch_pcap_pv_size is not none and (moloch_pcap_pv_size | int) != 0)

- name: Checking that pcap_disk is set
  fail:
    msg: "pcap_disk is not defined. Make sure it is defined in your inventory file. See sample inventory for help. You do not have to provide a value, but it must exist in the inventor file. Add pcap_disk: to any device in the ceph group."
  when: inventory_hostname in groups['moloch'] and pcap_disk is not defined

- name: Checking that moloch_threads is set
  fail:
    msg: "moloch_threads is not defined. Make sure it is defined in your inventory file. See sample inventory for help."
  when: inventory_hostname in groups['sensors'] and moloch_threads is not defined or moloch_threads is none

- name: Ensure ceph_disks is defined when use_ceph_for_pcap
  fail:
    msg: "ceph_disks must be defined when use_ceph_for_pcap is true.  Please review inventory file."
  when: use_ceph_for_pcap is defined
    and use_ceph_for_pcap == true
    and ceph_disks is not defined
    and ceph_disks is none

- name: Ensure ceph_disks is a list
  fail:
    msg: "ceph_disks must be a list of disks. Please review inventory file."
  when: use_ceph_for_pcap is defined
    and use_ceph_for_pcap == true
    and ceph_disks is defined
    and (ceph_disks is string or ceph_disks is not iterable)

...
