######################################################
################# Setup Metricbeat ###################
######################################################
---

- name: 'Install python-docker-py'
  yum:
    name: 'python-docker-py.noarch'
    state: 'installed'

#- name: Download Kube State Metric Containers
#  docker_image:
#    name: "{{ item }}"
#  with_items:
#    - tfplenum/kube-state-metrics-amd64:{{ kube_state_metrics_version }}
#    - tfplenum/kube-state-metrics:{{ kube_state_metrics_version }}
#    - docker.elastic.co/beats/metricbeat:{{ metricbeat_version }}

- name: "Create config directory"
  file:
    path: "{{ metricbeat_dir }}"
    state: directory
    owner: root
    group: root
    mode: u+rw,g+rw

- name: Install templates
  template:
    src: "templates/metricbeat-kubernetes.yaml.j2"
    dest: "{{ metricbeat_dir }}/metricbeat-kubernetes.yaml"
    group: root
    owner: root
    mode: 0644

- name: Flush Metricbeat Config
  command: "kubectl delete -f {{ metricbeat_dir }}/metricbeat-kubernetes.yaml --ignore-not-found=true"

- name: Deploy Services
  import_role:
    name: kubernetes/common
    tasks_from: kube_create.yml
  vars:
    name: "Metricbeat"
    file_name: "{{ metricbeat_dir }}/metricbeat-kubernetes.yaml"

- name: Wait for Metricbeat to be ready
  import_role:
    name: kubernetes/common
    tasks_from: kube_wait
  vars:
    type: "deployments"
    namespace: "kube-system"
    resource_name: "metricbeat"
    label: ""

...
