---
kind: Service
apiVersion: v1
metadata:
  name: grr-frontend
  namespace: default
spec:
  selector:
    name: grr-frontend
  ports:
  - name: agent
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: ui
    protocol: TCP
    port: 443
    targetPort: 443    
  type: LoadBalancer
