######################################################
################# Setup Kibana #######################
######################################################
---

- name: "Create config directory"
  file:
    path: "{{ kibana_dir }}"
    state: directory
    owner: root
    group: root
    mode: u+rw,g+rw

- name: Install templates
  template:
    src: "templates/{{ item }}.yml.j2"
    dest: "{{ kibana_dir }}/{{ item }}.yml"
    group: root
    owner: root
    mode: 0644
  with_items:
    - deploy
    - svc

- name: Flush Deployments
  shell: |
    kubectl --kubeconfig {{ kubernetes_conf_file }} delete -f {{ kibana_dir }}/{{ item }}.yml
    while [ $(kubectl --kubeconfig {{ kubernetes_conf_file }} get -f {{ kibana_dir }}/{{ item }}.yml | tail -n +2 | wc -l) != '0' ]; do
      echo -n .;
      sleep 1;
    done;
  with_items:
    - deploy
    - svc
  ignore_errors: true

- name: Deploy Services
  import_role:
    name: kubernetes/common
    tasks_from: kube_create
  vars:
    name: "Kibana Service"
    file_name: "{{ kibana_dir }}/svc.yml"

- name: Deploy Services
  import_role:
    name: kubernetes/common
    tasks_from: kube_create
  vars:
    name: "Kibana"
    file_name: "{{ kibana_dir }}/deploy.yml"

- name: Wait for kibana to be ready
  import_role:
    name: kubernetes/common
    tasks_from: kube_wait
  vars:
    type: "deployments"
    namespace: "default"
    resource_name: "kibana"
    label: ""

- name: Get Elasticsearch Service IP
  shell: "kubectl get svc -n default | grep 'elasticsearch ' | awk '{print $4}'"
  register: es_svc_ip

- name: Get Kibana Service IP
  shell: "kubectl get svc -n default | grep 'kibana' | awk '{print $4}'"
  register: kibana_svc_ip

- name: Wait for Kibana Service to become Available
  wait_for:
    host: "{{ kibana_svc_ip.stdout }}"
    port: 80
    delay: 30
    timeout: 300
  delegate_to: localhost

- name: Wait for Kibana to become healthy
  uri:
    url: "http://{{ kibana_svc_ip.stdout }}/api/status"
    return_content: yes
  register: results_kibana
  until: (results_kibana.status == 200) and (results_kibana.json.status.overall.state == 'green')
  retries: 20
  delay: 5

- name: Load Dashboards
  uri:
    url: "http://{{ kibana_svc_ip.stdout }}:80/api/kibana/dashboards/import?force=true"
    method: POST
    body_format: json
    headers:
      kbn-xsrf: y
    body: "{{ lookup('file', '{{ item }}')}}"
    status_code: 200, 201
  with_fileglob:
    - "files/dashboards/*.json"

- name: Set Default Kibana Pattern
  uri:
    url: "http://{{ kibana_svc_ip.stdout }}:80/api/kibana/settings/defaultIndex"
    method: POST
    body_format: json
    headers:
      kbn-xsrf: y
    body:
      value: "logstash-*"
    status_code: 200, 201
