---

- import_tasks: 00_preflight.yml

- name: Set hostname
  command: "hostnamectl set-hostname {{inventory_hostname}}"

- name: Check hostname
  command: "hostname -f"
  register: hostname

#- name: Change the hostname to our standard
#  hostname:
#    name: "{{ inventory_hostname }}"
#  register: hostname

- debug: "msg={{ansible_nodename}}"

- name: Validate ansible_nodename == inventory_hostname
  assert:
    that:
      ansible_nodename == inventory_hostname

- import_tasks: 05_configure_dnsmasq.yml
  when: inventory_hostname in groups['master-server']

- import_tasks: 10_update_dns.yml
  when: inventory_hostname not in groups['master-server']
  tags:
    - update-dns

...
