---
- name: Check Swap
  shell: "swapon --show=NAME --noheadings | wc -l"
  register: swap_result

- name: Swap Off
  command: swapoff --all
  when: swap_result is defined and swap_result.stdout != "0"

- name: 'Remove swap'
  mount:
    path: swap
    state: absent

...
