#######################################################
###################  Kubernetes Install ###############
#######################################################
---

- name: 'Install Kubernetes packages'
  yum:
    name:
      - "kubeadm-{{ kube_rpm_version }}"
      - "kubelet-{{ kube_rpm_version }}"
      - "kubectl-{{ kube_rpm_version }}"
    state: installed
    allow_downgrade: yes
  register: installed_packages
  notify:
    - restart kubelet

- name: 'Install Kubernetes support packages'
  yum:
    name:
      - "docker"
      - "device-mapper-persistent-data"
      - "lvm2"
      - "ebtables"
      - "ethtool"
    state: installed
  register: installed_packages
  notify:
    - restart docker

...