#######################################################
###################  Kubernetes Common ###############
#######################################################
---

- name: Reset Kube
  import_role:
    name: kubernetes/reset

- import_tasks: 00_preflight.yml

- import_tasks: 05_disable_swap.yml
- import_tasks: 10_kernel_mods.yml
- import_tasks: 15_sysctl.yml

- import_tasks: 25_install.yml
- import_tasks: 30_services.yml
- import_tasks: 35_env.yml
- import_tasks: 40_cred_dir.yml
- meta: flush_handlers

...
