#   Run with: ansible-playbook -i inventory/<YOUR_INVENTORY> generate_ssh_keys.yml --ask-pass

---

- name: Fail if ask-pass is missing
  fail:
    msg: "Error: Missing ask-pass. You need to add '--ask-pass' to the end of your command"
  when: ansible_ssh_pass is undefined or (ansible_ssh_pass is defined and ansible_ssh_pass == '') 

- name: Install sshpass
  yum:
    name: "sshpass"
    state: installed

- name: Install bind-utils
  yum:
    name: "bind-utils"
    state: installed

- name: Delete existing ssh information
  file:
    path: /root/.ssh
    state: absent

- name: Generate root SSH key
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    state: present

...
