---
- name: Configure RockNSM online repos
  yum_repository:
    file: rocknsm
    name: "rocknsm_2_3"
    enabled: "{{ rock_online_install }}"
    description: "rocknsm_2_3"
    baseurl: "{{ rocknsm_baseurl }}"
    repo_gpgcheck: 1
    gpgcheck: yes
    gpgkey:
      - file:///etc/pki/rpm-gpg/RPM-GPG-KEY-RockNSM-pkgcloud-2_3
      - file:///etc/pki/rpm-gpg/RPM-GPG-KEY-RockNSM-2
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
    cost: 750
    state: present
  when: "{{ docket_install == 'yumrepo' }}"

- name: Install packages
  yum:
    name:
      - docket
      - lighttpd
    state: present
